# Generated by Django 4.2 on 2023-12-16 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLevel1',
            fields=[
                ('level1ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AccountLevel2',
            fields=[
                ('level2ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level1ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlevel1')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLevel3',
            fields=[
                ('level3ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level2ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlevel2')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_accounts', to=settings.AUTH_USER_MODEL)),
                ('level3ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlevel3')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
