# Generated by Django 4.2 on 2023-12-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_id_alter_companybranch_id'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_accounts', to='company.companybranch'),
        ),
        migrations.AddField(
            model_name='account',
            name='company_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_accounts', to='company.company'),
        ),
    ]
