# Generated by Django 4.2 on 2023-12-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_company_branch_account_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='level1ID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlevel1'),
        ),
        migrations.AddField(
            model_name='account',
            name='level2ID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlevel2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='level3ID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountlevel3'),
        ),
    ]
