# Generated by Django 4.2 on 2023-12-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_level1id_account_level2id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlevel1',
            name='level1ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
