# Generated by Django 4.2 on 2023-12-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_accountid_alter_accountlevel2_level2id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_code',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
