# Generated by Django 4.2 on 2023-12-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
