# Generated by Django 4.2 on 2023-12-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
