# Generated by Django 4.2 on 2023-12-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_alter_company_id_alter_companybranch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personsID', models.AutoField(primary_key=True, serialize=False)),
                ('persons_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('leave', 'Leave')], max_length=5)),
                ('person_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=10)),
                ('company_branch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='company.companybranch')),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='company.company')),
            ],
        ),
    ]
