# Generated by Django 4.2 on 2023-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='user_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
