# Generated by Django 4.2 on 2023-12-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('persons', '0002_person_mobile2_person_occupation_person_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
