# Generated by Django 4.2 on 2023-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_alter_person_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
