# Generated by Django 4.2 on 2023-12-23 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0008_document_name'),
        ('inventory', '0003_alter_inventory_supplierid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0006_alter_person_user_name'),
        ('company', '0004_alter_company_id_alter_companybranch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('inv_transID', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expense_type', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('status', models.CharField(choices=[('Inventory Purchase', 'Inventory Purchase'), ('Inventory Use', 'Inventory Use'), ('Return to Inventory', 'Return to Inventory'), ('Return to Supplier', 'Return to Supplier')], max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_branch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.companybranch')),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.document')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_inventory_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
