# Generated by Django 4.2 on 2023-12-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='status',
            field=models.CharField(choices=[('inventory-purchase', 'Inventory Purchase'), ('inventory-use', 'Inventory Use'), ('return-to-inventory', 'Return to Inventory'), ('return-to-supplier', 'Return to Supplier')], max_length=20),
        ),
    ]
