# Generated by Django 4.2 on 2023-12-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_accountid'),
        ('inventory_transaction', '0002_alter_inventorytransaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorytransaction',
            old_name='customer',
            new_name='supplier',
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_expense_type', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_vehicle_type', to='accounts.account'),
        ),
    ]
