# Generated by Django 4.2 on 2023-12-23 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_account_level1id_account_level2id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationCategory',
            fields=[
                ('accu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('year_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('depreciation_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_month', models.DateField()),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('identification', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('accu_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fixed_assets.depreciationcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationProcess',
            fields=[
                ('depreciation_process_id', models.AutoField(primary_key=True, serialize=False)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('depreciation_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fixed_assets.fixedasset')),
            ],
        ),
    ]
