# Generated by Django 4.2 on 2023-12-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0002_fixedasset_company_branch_fixedasset_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='depreciation',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
    ]
