# Generated by Django 4.2 on 2023-12-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0005_alter_fixedasset_depreciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciationcategory',
            name='accu_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='depreciation',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=3),
        ),
    ]
