# Generated by Django 4.2 on 2023-12-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0006_alter_depreciationcategory_accu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='depreciation_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
