# Generated by Django 4.2 on 2023-12-23 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0003_account_level1id_account_level2id_and_more'),
        ('persons', '0006_alter_person_user_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_transactions',
                                   to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.document')),
                ('updated_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_transactions',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
