# Generated by Django 4.2 on 2023-12-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_document_created_by_document_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
