# Generated by Django 4.2 on 2023-12-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
