# Generated by Django 4.2 on 2023-12-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_document_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
