# Generated by Django 4.2 on 2023-12-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_account_level1id_account_level2id_and_more'),
        ('persons', '0006_alter_person_user_name'),
        ('company', '0004_alter_company_id_alter_companybranch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('measureID', models.AutoField(primary_key=True, serialize=False)),
                ('measure', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryID', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_item_name', models.CharField(max_length=255)),
                ('inventory_type', models.CharField(max_length=255)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detail', models.TextField()),
                ('note', models.TextField()),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('company_branch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.companybranch')),
                ('company_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.measures')),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
        ),
    ]
