# Generated by Django 4.2 on 2023-12-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_supplierid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='avg_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
